spring:
  application:
    name: elastic-app
  elasticsearch:
    jest:
      uris: http://192.168.99.100:9200
  data:
    elasticsearch:
      cluster-nodes: 192.168.99.100:9300
#      cluster-name: es-app
  profiles:
    active: local
#    active: default
server:
  port: 8007
