server:
  port: 8005
spring:
  application:
    name: zipkin-demo
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts:
       - 192.168.99.100:9300
      httpLogging: HEADERS

logging:
  level:
    root: debug
